replicaCount: 1

image:
  repository: vyacheslavoleshko
  pullPolicy: IfNotPresent

postgresql:
  postgresqlUsername: poxstgres
  postgresqlPassword: secretpass
  postgresqlDatabase: postgres
  service:
    port: "5432"

service:
  type: ClusterIP
  port: 80
